repos:
  - repo: local
    hooks:
      - id: verible-verilog-format
        name: Verible Verilog Formatter
        entry: verible-verilog-format
        args:
          - --indentation_spaces=4
          - --wrap_spaces=4
          - --column_limit=80
          - --try_wrap_long_lines=true
          - --assignment_statement_alignment=align
          - --enum_assignment_statement_alignment=align
          - --module_net_variable_alignment=align
          - --struct_union_members_alignment=align
          - --class_member_variable_alignment=align
          - --distribution_items_alignment=align
          - --port_declarations_alignment=align
          - --port_declarations_indentation=wrap
          - --formal_parameters_alignment=align
          - --formal_parameters_indentation=wrap
          - --named_port_alignment=align
          - --named_port_indentation=wrap
          - --named_parameter_alignment=align
          - --named_parameter_indentation=wrap
          - --inplace
        language: system
        files: \.(v|sv)$

      - id: verible-verilog-syntax
        name: Verible Verilog Syntax Check
        entry: verible-verilog-syntax
        language: system
        files: \.(v|sv)$
